export enum PublicationTagEnum {
  MATHEMATICS = 'Mathématiques',
  HISTORY = 'Histoire',
  GEOGRAPHY = 'Géographie',
  LIFE_AND_EARTH_SCIENCES = 'SVT',
  PHYSICS = 'Physique',
  CHEMISTRY = 'Chimie',
  SPORT = 'Sport',
  TECHNOLOGY = 'Technologie',
  ARTS = 'Arts',
  MUSIC = 'Musique',
  PHILOSOPHY = 'Philosophie',
  ECONOMICS = 'Économie',
  COMPUTER_SCIENCE = 'Informatique',
  ARABIC = 'Arabe',
  ENGLISH = 'Anglais',
  FRENCH = 'Français',
  SPANISH = 'Espagnol',
  GERMAN = 'Allemand',
  ITALIAN = 'Italien',
}
