// export enum PublicationTagEnum {
//   MATHEMATICS = 'Mathématiques',
//   HISTORY = 'Histoire',
//   GEOGRAPHY = 'Géographie',
//   LIFE_AND_EARTH_SCIENCES = 'SVT',
//   PHYSICS = 'Physique',
//   CHEMISTRY = 'Chimie',
//   SPORT = 'Sport',
//   TECHNOLOGY = 'Technologie',
//   ARTS = 'Arts',
//   MUSIC = 'Musique',
//   PHILOSOPHY = 'Philosophie',
//   ECONOMICS = 'Économie',
//   COMPUTER_SCIENCE = 'Informatique',
//   ARABIC = 'Arabe',
//   ENGLISH = 'Anglais',
//   FRENCH = 'Français',
//   SPANISH = 'Espagnol',
//   GERMAN = 'Allemand',
//   ITALIAN = 'Italien',
// }
export enum PublicationTagEnum {
  MATHEMATICS = 'MATHEMATICS',
  HISTORY = 'HISTORY',
  GEOGRAPHY = 'GEOGRAPHY',
  LIFE_AND_EARTH_SCIENCES = 'LIFE_AND_EARTH_SCIENCES',
  PHYSICS = 'PHYSICS',
  CHEMISTRY = 'CHEMISTRY',
  SPORT = 'SPORT',
  TECHNOLOGY = 'TECHNOLOGY',
  ARTS = 'ARTS',
  MUSIC = 'MUSIC',
  PHILOSOPHY = 'PHILOSOPHY',
  ECONOMICS = 'ECONOMICS',
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  ARABIC = 'ARABIC',
  ENGLISH = 'ENGLISH',
  FRENCH = 'FRENCH',
  SPANISH = 'SPANISH',
  GERMAN = 'GERMAN',
  ITALIAN = 'ITALIAN',
}
